### ISSUE TITLE
Question on modelling polycrystalline material

### ISSUE THREAD

**Issue by will-colea** [ubermag/workshop#13]
Hello -

I know that vornoi plots can be used to model polycrystalline structure. Is there a way to implement this into ubermag? I have seen a paper on this for oommf, but I am not sure how to call the vornoi function in ubermag (https://go.gale.com/ps/anonymous?id=GALE%7CA199027902&sid=googleScholar&v=2.1&it=r&linkaccess=abs&issn=1044677X&p=AONE&sw=w). 

Thank you for creating this library. I am really liking the package so far.

**Comment by marijanbeg** [comment]
Hi @will-colea, thank you for you question. This is not something we covered in Ubermag, but if this is something you need, we can consider including it in the next release.
