### ISSUE TITLE
Windows 10 Miniconda run error

### ISSUE THREAD

**Issue by p-brane** [ubermag/workshop#16]
I installed Miniconda on my Windows 10 machine and get an error when running conda. 

 `C:\ProgramData\Miniconda3\condabin>conda list
Fatal Python error: initfsencoding: unable to load the file system codec
  File "C:\lyx-233\Python\Lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\`

I have PyCell and and Lyx installed and think that Miniconda is finding these installs instead. I've tried adding `C:\ProgramData\Miniconda3\condabin` to my PATH, to my PYTHONPATH and to my PYTHONHOME but none of these seem to help. Do anyone have suggestions on how to fix it?

**Comment by marijanbeg** [comment]
Hi @p-brane, thank you for your question. Are you in Anaconda Prompt or just command prompt? Have you activated the environment (`conda activate ...`)?

**Comment by p-brane** [comment]
Hi @marijanbeg 
I get the error from the Administrator Anaconda prompt immediately after it opens, when I type conda list, and in a command prompt when I type conda list. I get the same result when I run the prompts as Administrator too.

**Comment by catrevil** [comment]
It may have something to do with the depth to which miniconda would have to search to find the installation of python. What happens when you call for  `conda -h`? I might recommend moving the relevant installation of miniconda higher up in your directory tree. If my nomenclature is not proper (this is likely), I mean to say you should move your installation of miniconda to just under the `C:\` directory. I note that your lyx install is as such, and as you reference, is likely the cause. (Actually you might try putting the miniconda install path at the beginning of your path environment variable list!)

**Comment by marijanbeg** [comment]
Hi @p-brane and @catrevil, I am not familiar with lyx at all and I would suggest changing the order of paths as well. Also, please try to google for the problem -  I assume it should be possible to have both lyx and conda on the same host.

**Comment by gaurav123shukla** [comment]
During installing miniconda check both box one of them is related to envirounment. Then in prompt you saw 'base'. Then type conda activate ubermag pythom=3.8

**Comment by marijanbeg** [comment]
Hi @p-brane, has this issue been resolved?

**Comment by p-brane** [comment]
Hi @marijanbeg ,
I got distracted by a failing hard drive and I'm back to troubleshooting this. I think at this point I'll just uninstall Lyx (LaTeX editor) and see if that fixes it. I discovered and have become enamored with Atom and the Markdown with the Markdown-Enhanced-Prevew plugin so don't expect to use Lyx much even though Lyx is very good. 

python -V show version 2.6.6.
Changing PATH, PYTHONPATH, and PAYTHONHOME to include 'C:\ProgramData\Miniconda3\condabin' and  'C:\ProgramData\Miniconda3' didn't help. I moved the path to the top too.

**Comment by p-brane** [comment]
Hi @marijanbeg ,
I got distracted by a failing hard drive and I'm back to troubleshooting this. I think at this point I'll just uninstall Lyx (LaTeX editor) and see if that fixes it. I discovered and have become enamored with Atom and the Markdown with the Markdown-Enhanced-Prevew plugin so don't expect to use Lyx much even though Lyx is very good. 

python -V show version 2.6.6.
Changing PATH, PYTHONPATH, and PAYTHONHOME to include 'C:\ProgramData\Miniconda3\condabin' and  'C:\ProgramData\Miniconda3' didn't help. I moved the path to the top too.

**Comment by marijanbeg** [comment]
Hi @p-brane, thank you for letting us know. I hope you managed to fix your Anaconda installation.

**Comment by p-brane** [comment]
Hi @marijanbeg 
After a lot of trial and error, I was not able to get conda to function when paths to other python installations were present. I remove path to lyx-233/python and PyCellStudy/python to get conda to "work".

The latest miniconda3 windows installer installs conda 4.8.3 and python 3.7.7. If you` conda update conda` and `conda update python` you get python 3.8.3 but then conda generates errors and does not function. I uninstalled miniconda and installed it got get back to a working version.

I created the environment with python 3.7 and installed ubermag. The ubermag install failed because the notebook module was not found. I installed jupyter to get the notebook module with `pip install jupyter`. The install of ubemag completed.

Running the test using `python -c "import ubermag; ubermag.test()"` generates the error `ModuleNotFoundError: No module named 'ubermag'`. `conda list` shows ubermag 0.23. I added `C:\Users\<user name>\Documents\.conda\envs\ubermag\Lib\site-packages` to the PYTHONPATH to get it run. The test reports 79 failed tests now.

I'll try and track down the following errors next.
 `>       raise EnvironmentError('Cannot find OOMMF.')
E       OSError: Cannot find OOMMF.
..\..\..\.conda\envs\ubermag\Lib\site-packages\oommfc\oommf\oommf.py:388: OSError`
and

```
=========================== short test summary info ===========================
FAILED tests/test_field.py::TestField::test_mpl_scalar - _tkinter.TclError: C...
FAILED tests/test_field.py::TestField::test_mpl_vector - _tkinter.TclError: C...
FAILED tests/test_field.py::TestField::test_mpl - _tkinter.TclError: Can't fi...
FAILED tests/test_field.py::TestField::test_plot_large_sample - _tkinter.TclE...
FAILED tests/test_field.py::TestMesh::test_mpl - _tkinter.TclError: Can't fin...
FAILED tests/test_field.py::TestMesh::test_k3d_mpl_subregions - _tkinter.TclE...
FAILED tests/test_line.py::TestLine::test_mpl - _tkinter.TclError: Can't find...
FAILED tests/test_mesh.py::TestMesh::test_mpl - _tkinter.TclError: Can't find...
FAILED tests/test_mesh.py::TestMesh::test_k3d_mpl_subregions - _tkinter.TclEr...
FAILED tests/test_region.py::TestRegion::test_mpl - _tkinter.TclError: Can't ...
FAILED tests/test_table.py::TestTable::test_mpl - _tkinter.TclError: Can't fi...
FAILED tests/test_micromagnetictests.py::TestCompute::test_energy - OSError: ...
FAILED tests/test_micromagnetictests.py::TestCompute::test_energy_density - O...
FAILED tests/test_micromagnetictests.py::TestCompute::test_effective_field - ...
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_scalar_vector_vector
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_field_vector_vector
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_field_field_field
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_dict_vector_vector
FAILED tests/test_micromagnetictests.py::TestDamping::test_scalar - OSError: ...
FAILED tests/test_micromagnetictests.py::TestDamping::test_dict - OSError: Ca...
FAILED tests/test_micromagnetictests.py::TestDamping::test_field - OSError: C...
FAILED tests/test_micromagnetictests.py::TestDemag::test_demag - OSError: Can...
FAILED tests/test_micromagnetictests.py::TestDemag::test_demag_asymptotic_radius
FAILED tests/test_micromagnetictests.py::TestDMI::test_scalar - OSError: Cann...
FAILED tests/test_micromagnetictests.py::TestDMI::test_dict - OSError: Cannot...
FAILED tests/test_micromagnetictests.py::TestDynamics::test_scalar_scalar - O...
FAILED tests/test_micromagnetictests.py::TestDynamics::test_scalar_dict - OSE...
FAILED tests/test_micromagnetictests.py::TestDynamics::test_field_field - OSE...
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_zeeman - O...
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_uniaxialanisotropy
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_cubicanisotropy
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_dmi_zeeman
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_dmi_zeeman_uniaxialanisotropy_demag
FAILED tests/test_micromagnetictests.py::TestExchange::test_scalar - OSError:...
FAILED tests/test_micromagnetictests.py::TestExchange::test_dict - OSError: C...
FAILED tests/test_micromagnetictests.py::TestExchange::test_field - OSError: ...
FAILED tests/test_micromagnetictests.py::test_info_file - OSError: Cannot fin...
FAILED tests/test_micromagnetictests.py::TestMesh::test_single_nopbc - OSErro...
FAILED tests/test_micromagnetictests.py::TestMesh::test_multi_nopbc - OSError...
FAILED tests/test_micromagnetictests.py::TestMesh::test_single_pbc - OSError:...
FAILED tests/test_micromagnetictests.py::TestMesh::test_multi_pbc - OSError: ...
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_noevolver_nodriver
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_evolver_nodriver
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_noevolver_driver
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_evolver_driver
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_output_files - O...
FAILED tests/test_micromagnetictests.py::test_multiple_drives - OSError: Cann...
FAILED tests/test_micromagnetictests.py::TestPrecession::test_scalar - OSErro...
FAILED tests/test_micromagnetictests.py::TestPrecession::test_dict - OSError:...
FAILED tests/test_micromagnetictests.py::TestPrecession::test_field - OSError...
FAILED tests/test_micromagnetictests.py::TestRKKY::test_scalar - OSError: Can...
FAILED tests/test_micromagnetictests.py::TestSlonczewski::test_single_values
FAILED tests/test_micromagnetictests.py::TestSlonczewski::test_dict_values - ...
FAILED tests/test_micromagnetictests.py::TestSlonczewski::test_field_values
FAILED tests/test_micromagnetictests.py::test_stdprob3 - OSError: Cannot find...
FAILED tests/test_micromagnetictests.py::test_stdprob4 - OSError: Cannot find...
FAILED tests/test_micromagnetictests.py::test_stdprob5 - OSError: Cannot find...
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_noevolver_nodriver
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_rungekutta_evolver_nodriver
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_euler_evolver_nodriver
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_noevolver_driver
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_noprecession - ...
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_nodamping - OSE...
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_output_files - ...
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_scalar_vector
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_field_vector
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_scalar_field
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_field_field
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_dict_vector
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_field_dict
FAILED tests/test_micromagnetictests.py::TestZeeman::test_vector - OSError: C...
FAILED tests/test_micromagnetictests.py::TestZeeman::test_dict - OSError: Can...
FAILED tests/test_micromagnetictests.py::TestZeeman::test_field - OSError: Ca...
FAILED tests/test_micromagnetictests.py::TestZhangLi::test_scalar_scalar - OS...
FAILED tests/test_micromagnetictests.py::TestZhangLi::test_dict_scalar - OSEr...
FAILED tests/test_micromagnetictests.py::TestZhangLi::test_field_scalar - OSE...
FAILED tests/test_oommf.py::test_get_oommf_runner - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_overhead - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_runtimeerror - OSError: Cannot find OOMMF.
= 79 failed, 219 passed, 1 skipped, 5 deselected, 30 warnings in 63.74s (0:01:03) =
```

**Comment by catrevil** [comment]
When you create the environment within ubermag, you should specify the python version as 3.8, not 3.7 — what happens if you try this?

Funny enough, I think the notebook extension got removed the last time I updated ubermag via `conda update ubermag` in `(ubermag)`.

I would not try to update the python within the `(base)` conda environment. Conda is really nice when it comes to managing dependencies, so if this does not change when you tell it to `conda update conda` in `(base)`, I would assume not to change this manually.

I am actually using 2.0a2 from a non-conda install of oommf, and I have not ran into issues related to this. Conda will supply the proper tcl packages needed when you `conda install ubermag` in `(ubermag)`.

**Comment by marijanbeg** [comment]
I assume we are addressing this issue now as #33, so we continue the discussion there :)
