### ISSUE TITLE
Value error 

### ISSUE THREAD

**Issue by Harry-09** [ubermag/workshop#18]
So far all things were working well in following the instruction in the tutorial except i got a value error that trace back to the **"T" crystal class is not supported in win32** ?? can u help me in the correcting this error.
[error.pdf](https://github.com/ubermag/workshop/files/4835533/error.pdf)

**Comment by marijanbeg** [comment]
Hi @Harry-09, thank you for your question. On Windows, we use precompiled OOMMF for Windows, which does not contain T and D2d crystal class extensions. This is the reason why only built-in Cnv DMI is available. There is a way how to avoid this issue using Docker. I will prepare a tutorial about that and will let you know.
