### ISSUE TITLE
RKKY-type exchange interactions

### ISSUE THREAD

**Issue by fredrendell7** [ubermag/workshop#19]
I was just wondering if it is possible to specify an RKKY-type interaction within the micromagnetic model using ubermag (for example the Oxs_TwoSurfaceExchange in oommf). Thank you in advance

**Comment by marijanbeg** [comment]
Hi @fredrendell7, thank you for your question. I will try to make a tutorial how to deal with RKKY before the next session. Thank you for your patience.

**Comment by marijanbeg** [comment]
Hi @fredrendell7, thank you for your patience. Conda packages are now built and the tutorial is online (https://oommfc.readthedocs.io/en/latest/ipynb/rkky.html). I am also going to cover it tomorrow during the live session. Please update `conda update ubermag`.

I am going to close this issue now, but please feel free to reopen it.

**Comment by fredrendell7** [comment]
Hi @marijanbeg, thank you very much for your help and the very clear tutorial. Unfortunately, even after updating my ubermag environment using `conda update ubermag` I recieve the following error: `AttributeError: module 'micromagneticmodel' has no attribute 'RKKY'`. 

Thank you in advance!

**Comment by marijanbeg** [comment]
That is weird. Probably conda does not find the newer ubermag version in the cloud yet (sometimes it takes a day or two for a package to become available). You can try to be specific with the version: `conda install --channel conda-forge ubermag=0.23`. Although this line is an install command, it should simply update you ubermag installation.

**Comment by fredrendell7** [comment]
That did the trick! Working now on both my Windows and OSX machines. Doing `conda update ubermag` seemed to only update related packages and not ubermag, micromagneticmodel... etc. Thank you very much for your help with this!

**Comment by marijanbeg** [comment]
Wohoooo!!! `conda update ubermag` should work as well, but since the newest version is less than a day old, it takes some time for all metadata in the cloud to be updated (and this is something we have no influence on).
