### ISSUE TITLE
'Table' object is not subscriptable

### ISSUE THREAD

**Issue by yuxuanbc** [ubermag/workshop#2]
Hi, I have a problem when I try to ran the oommfc fmr standard problem on my computer. When I try to get the data of magnetization in the system.table. It report error: 'Table' object is not subscriptable. Sorry about that, do you have any idea what will cause this? 
Thank you so much!

![image](https://user-images.githubusercontent.com/67115880/85046893-0a3cfd00-b15f-11ea-8be9-3e6d8a98e0c5.png)

**Comment by marijanbeg** [comment]
Hi @yuxuanbc, where did you find that notebook? It is outdated.

It should be `system.table.data['mx']`

**Comment by yuxuanbc** [comment]
Oh, Thank you so much, I probably find it on the old oommfc web site several month ago,and forget to check it again. Thank you again for your kind help!

**Comment by marijanbeg** [comment]
Sure, please make sure everything is updated.

**Comment by yuxuanbc** [comment]
Sorry, but it's so nice for getting help here. 
Another question I have is this.
Is there a good way to do the Discretisedfield .ovf output for each step when I run the Timedriver?
Do I need to define many new drivers only for each step, and then output?
what I want to is to show the FMR mode at certain frequency. 
Thank you so much!

**Comment by marijanbeg** [comment]
Hi @yuxuanbc, when you call the time driver, you pass the number of steps you want saved:
```
td = oc.TimeDriver()
td.drive(system, t=0.5e-9, n=2000)  # t is the simulation time and n is the number of steps
```

Does this answer you question?

**Comment by yuxuanbc** [comment]
Thank you for your answer!
what I mean is that I hope to get the magnetizations for each cell at each time. Then I can rearrange the date and do time FFT for each cell.
Just like you mentioned in the code. If I don't understand it wrong, the system will drive 0.5ns with 2000 step. But I can only get 2000 averaged magnetization (in y direction for example ). Is there any way I can get 2000 .ovf file to show the magnetization for every cell inside the mesh?

Thank you so much!

**Comment by marijanbeg** [comment]
`TimeDriver` actually saves 2000 files as you want. In the same directory where you run your notebook a directory with the same name as the name you give to your system will be created. Inside, you can find the drive (probably the last one), which is going to have 2000 OMF files.

There is `micromagneticdata` package I am going to show in the last session, which makes the analysis of that kind easy.

I will close this issue now. Please raise a new issue for any new question. This way we make sure other participants can see the answers if they have the same question. :)

**Comment by yuxuanbc** [comment]
Thank you again. Will do if I have other questions! Sorry about that!

**Comment by marijanbeg** [comment]
No worries, keep asking.
