### ISSUE TITLE
Error in starting Jupyter from Anaconda

### ISSUE THREAD

**Issue by njaggi1** [ubermag/workshop#20]
I  followed the Youtube instructions to install miniconda3, on my Windows machine, then installed Ubermag, then created the ubermag-test directory, ran the test; it passed all tests. 

After that, I was following instructions to start Jupyter Notebook from Anaconda by typing the suggested command
 jupyter notebook &

Got an error message: The ampersand (& character ius not allowed. The & operator is reserved for future use; wrap an ampersand in double quotataion marks ("&") to pass it as part of a string.

I tried:  jupyter notebook "&"
Got a different error message: No such file or directory C:\Users\Jaggi\ubermag-test\&

![error starting jupyter from anaconda ](https://user-images.githubusercontent.com/40277387/85890722-8b297380-b7b3-11ea-8420-5fc86303623e.JPG)

**Comment by marijanbeg** [comment]
Hi @njaggi1, thank you for your question. You can ignore `&` completely. Just type `jupyter notebook` and press Return.

I will close this issue now, but please feel free to reopen it if this did not help.

**Comment by njaggi1** [comment]
I am a complete newbie to Jupyter, so I will appreciate a little bit of guidance.
I downloaded the example Jupyter notebooks from your Repository - while I was looking at them inside Binder- into a folder on my Desktop. But when I clicked on any of these downloaded .ipynb files, it asked me to link **_an app_** to the .ipynb file type; and I don't know what that ought to be.

So, I tried uploading them into my localhost tree (see screenshot). I was able to start and execute these files from there. So, I do have something to get started. But if there is a simpler, more efficient, neater, way of doing things, please point it out to me. Thanks for your help.
![localhost etc](https://user-images.githubusercontent.com/40277387/85934124-15510500-b8a4-11ea-96f0-be0ba5e9ab7f.JPG)

**Comment by marijanbeg** [comment]
Hi @njaggi1, thank you for your question. Yes, double-clicking `ipynb` file does not work. The way I use Jupyter is that in terminal (command prompt) I navigate to the directory where my notebook files are (`cd directory/where/my/files/are/...`) and then, when I am in, I start Jupyter (`jupyter notebook`). This way, Jupyter will find all notebooks in that directory and all its subdirectories and you will be able to open them.

I hope this help, please feel free to continue asking.
