### ISSUE TITLE
MinDriver Issue

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#23]
Thanks sir for kind suport. Sir when i move forward, i got a huge number of errors when i want to do minimization of system energy by Mindriver.Sir please see it. I am beginer so i am facing such basic type of problem sir.
![drive error](https://user-images.githubusercontent.com/67150548/85946459-79aaad80-b912-11ea-9be7-31e5f11e53e0.JPG)
![drive 2](https://user-images.githubusercontent.com/67150548/85946475-9ba43000-b912-11ea-86f4-05018ebd3298.JPG)

 
Email: gauravshukla571996@gmail.com

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, this issue is going to be addressed soon as a part of #15. Please have a look at comments there.
