### ISSUE TITLE
UniaxialAnisotropy energy

### ISSUE THREAD

**Issue by Lee-89757** [ubermag/workshop#24]
Hi, Sir. I am wondering if we can add mutiple UniaxialAnisotropy term in Ubermag. I tried this and it said just one UniaxialAnisotropy term was allowed. But as I know, in OOMMF, we can put as many as we want as long as they have different names. And I also tried put a name value in mm.UniaxialAnisotropy() but it seems to be invalid. So how can I add another UniaxialAnisotropy term in one system?

Thank you very much!

**Comment by marijanbeg** [comment]
Hi @Lee-89757, thank you for your question. We are making a tutorial on this topic and we will cover it tomorrow during the live session. As soon as the tutorial is completed, I will add a link here, so you do not have to wait until tomorrow.

**Comment by marijanbeg** [comment]
Hi @Lee-89757, thank you for your patience. Please update ubermag (`conda update ubermag`) and have a look at this short tutorial: https://oommfc.readthedocs.io/en/latest/ipynb/multiple-terms.html

I am going to cover it during tomorrow's live session as well.

**Comment by Lee-89757** [comment]
Thank you very much and it helps me a lot
