### ISSUE TITLE
Stress terminology

### ISSUE THREAD

**Issue by code-whale** [ubermag/workshop#25]
Dear Ubermag team,
I would like to ask about whether you can add stress parameters to the simulation, and if so, can you tell me how, and then I see that you have also added RKKY coupling, will it be updated in the near future?

**Comment by marijanbeg** [comment]
Hi @code-whale, what do you mean by stress parameters? Do you mean the magnetoelastic effects? Have a look at the `MagnetoElastic` class documentation. However, the use of this class for OOMMF requires you have that extension in your compiled OOMMF.

RKKY is in ubermag and will be built hopefully by the end of the day.

**Comment by code-whale** [comment]
Thank you for your answer. I found the magnetoelastic extension of oommf, but I don't know how to set it on ubermag. Where is your MagnetoElastic class documentation? I don't seem to find it.

**Comment by marijanbeg** [comment]
Hi @code-whale, i have just seen your comment here. To make sure I see it on time, could you please reopen it so we know we need to address it. Here is the API for MagnetoElastic class: https://micromagneticmodel.readthedocs.io/en/latest/magnetoelastic.html
