### ISSUE TITLE
Setting negative exchange constant in antiferromagnetic material

### ISSUE THREAD

**Issue by code-whale** [ubermag/workshop#29]
Dear Ubermag team,
I am simulating a FM/AFM interlayer coupling material. In the process of simulation, I found that I need to set a negative interlayer exchange constant in AFM, but I don't seem to be able to make A < 0. Is there any way to solve this problem? in addition, I also found that the exchange energy density (Ai) in the model is defined in J / m ^ 2. How should I define this term? Can you help me solve this problem?
![image](https://user-images.githubusercontent.com/61874432/86124268-6e6fa180-bb0d-11ea-8b9c-ce989e55f2cc.png)

![image](https://user-images.githubusercontent.com/61874432/86124218-5566f080-bb0d-11ea-9858-10dfe7dda20b.png)
![image](https://user-images.githubusercontent.com/61874432/86124250-61eb4900-bb0d-11ea-8e8f-1dd72a90ad4c.png)

**Comment by code-whale** [comment]
Great, I updated the new version, this problem has been solved, thanks to the hard work of the ubermag team

**Comment by marijanbeg** [comment]
Hi @code-whale, new Ubermag conda packages are being built at the moment, so I am a bit confused how you updated Ubermag? :) Did you use pip?

**Comment by code-whale** [comment]
Yes, I updated the package using pip, but I made an error when I ran the RKKY parameter Yes. Is that why I didn't configure it properly?
I attached the error message in the following picture.
![image](https://user-images.githubusercontent.com/61874432/86214410-be05aa00-bbad-11ea-8151-7a6b55c77204.png)
![image](https://user-images.githubusercontent.com/61874432/86214474-d2e23d80-bbad-11ea-8fa6-62e92e64d7f3.png)

**Comment by marijanbeg** [comment]
Yes, it takes a day or two for all conda packages to be built and I hope it will be completed by the end of the day. I will let you know when this is done. These updates will also simplify and address other issues raised during the workshop. Thank you for your patience.

**Comment by code-whale** [comment]
OK, thank you for your answer. I'll be waiting for your notice, but I'd like to ask if I need to downgrade my updated package now. And after you update with conda in the future, do I need to delete the existing ubermag on my computer and re-use conda to build the environment? Because I've been using pip all the time.

**Comment by marijanbeg** [comment]
Hi @code-whale, the best approach would be to just create a new conda environment and run `conda install --channel conda-forge ubermag`. From that point, whenever you need to update, you just type `conda update ubermag`. `pip` is also fine, but using conda is much easier and it is something we recommend. Thank you for you patience.

**Comment by code-whale** [comment]
Thank you for your patient answer. I will try to create a new conda environment. Thank you for your help.

**Comment by code-whale** [comment]
I followed your tutorial on YouTube to try to build ubermag, with conda on mac, but at run time, there seems to be a conflict between the oommf in the ubermag package and the oommf that I have configured, resulting in an error. What should I do, modify the environment variables?
![image](https://user-images.githubusercontent.com/61874432/86241294-43508500-bbd5-11ea-92a4-c07c6eabbdf7.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, do you have an environment variable set? If yes, you can delete it. When you install ubermag using conda everything should be automatic.

**Comment by marijanbeg** [comment]
Thank you for your patience, ubermag packages are now built and you can update ubermag (`conda update ubermag`). After that, you can have a look at the short tutorial: https://oommfc.readthedocs.io/en/latest/ipynb/negative-A.html

I am going to cover it during the live session tomorrow as well.

As always, for any other questions, please raise an issue :)
