### ISSUE TITLE
minimization driver

### ISSUE THREAD

**Issue by mzubair1** [ubermag/workshop#30]
I am using the cammand
md = mc.MinDriver()
md.drive(system)

system.m.plane('z').mpl()
when I press shift enter, it says docker was not found.
I donot know what I am doing wrong

**Comment by catrevil** [comment]
I presume you are running this locally? What precisely does the error say? Can you copy and paste this in a code formatted reply?

````
Code formatting looks like this!
````

**Comment by marijanbeg** [comment]
Hi @mzubair1, thank you for your question. This error means that ubermag is not installed properly and OOMMF cannot be found. Have you followed the installation instructions? If yes, please give us more details and we will be able to help.

**Comment by mzubair1** [comment]
Hello Professor I followed your installation video and I installed the things properly but I didnot installed oommf on my linux. Do I need to install oomf on linux serperately? I am runing all other commands on jupyternotebook .I donot know where the problem occurs.

**Comment by marijanbeg** [comment]
Hi @mzubair1, if you installed Ubermag using Miniconda, then everything should be installed and set up. If the problem persists, we can arrange a Skype/Zoom meeting and I can guide you through the process.

**Comment by mzubair1** [comment]
I thing so it would be great if you guide me. throguh zoom meeting. I be grateful to you.I am newcomer and didnot know how to fix the probelm.

**Comment by mzubair1** [comment]
My zoom id is 3905126138

**Comment by marijanbeg** [comment]
Can you use this link? https://us02web.zoom.us/j/86434405183?pwd=cWQxMGtTUEJnNUsweGlsM0RId255UT09
I will be there for the next 10 minutes.

**Comment by marijanbeg** [comment]
I am not there anymore, and I deleted the link. Please let me know when you are going to be available. It is a bit late in the UK, so i suggest we do that tomorrow.

**Comment by mzubair1** [comment]
ok
*Muhammad Zubair*
Room # 305A
PhD Candidate
Department of Physics and Astronomy
University of Delaware
Cell: 001-302-5103927

**Comment by mzubair1** [comment]
Ok, I will ask you after the tomorrow's session. Thanks
*Muhammad Zubair*
Room # 305A
PhD Candidate
Department of Physics and Astronomy
University of Delaware
Cell: 001-302-5103927

**Comment by mzubair1** [comment]
The probelm is solved.Thanks for your help and your prompt reply.I open so many pages if juptyernotebook and delete the old one and then run the command again, it works. Thanks again for investing time on me.

**Comment by marijanbeg** [comment]
Great, thank you for letting us know.
