### ISSUE TITLE
Vortex relaxation

### ISSUE THREAD

**Issue by PkRPintu** [ubermag/workshop#31]
Hi Marijan,

Thanks for the very interesting and informative lectures on Ubermag.  I have a very small question, it can be some mistake done by me too.

In my case, when relaxing the vortex state without applying any external magnetic field at all why the vortex state is getting vanished and getting relaxed into a ferromagnetic state? I attach a picture for the same here too. I am not using the Binder and trying to do it in the Jupyter notebook from anaconda platform of my pc.

Thanks a lot.
![Screenshot (24)](https://user-images.githubusercontent.com/59337225/86270887-45621600-bbcc-11ea-80c7-bb4ca47ac08e.png)

**Comment by marijanbeg** [comment]
Hi @PkRPintu, thank you for your question. I cannot see what is happening in the notebook. Can you please send me the notebook, so I can see what changes caused this.

**Comment by PkRPintu** [comment]
Hi @marijanbeg , Sure, I created a github repository with the notebook file and invited you. I hope you can see it now. If not, then please do let me know so I will send you the file by other means. Thanks a lot for your help. I really appreciate it.

Best wishes
Pradeep

**Comment by PkRPintu** [comment]
Hi @marijanbeg , Here I attach the notebook in the pdf format. Thanks a lot.

[vortex-dynamics.pdf](https://github.com/ubermag/workshop/files/4859403/vortex-dynamics.pdf)

**Comment by marijanbeg** [comment]
Thank you! Your Ms is `8e-5`, which is very small and demag has no effect. Ms is usually in the order of 10^5, 10^6. So if you change `Ms = 8e-5` to `Ms=8e5`, everything works as expected.

**Comment by PkRPintu** [comment]
Hi @marijanbeg , Aha, I am sorry for my silly mistake. Thanks a lot for the help. Now, it works perfectly fine.
