### ISSUE TITLE
MIF File to IPYNB file

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#32]
Dear sir
As in jupyter notebook we can see the mif file corresponding to input we insert. Sir Is there is any way to convert mif file into ipynb file.

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, unfortunately, there is no way of converting MIF to ipynb files. This is code-wise not an easy task and this is something we do not intend to do in future ubermag versions.
