### ISSUE TITLE
Unbound local error

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#34]
Sir now runtime error is removed after installing docker but new type of error showing.
![docker1](https://user-images.githubusercontent.com/67150548/86484343-05ae4200-bd24-11ea-87e0-eea410c5882a.JPG)
 
![docker](https://user-images.githubusercontent.com/67150548/86484306-f3340880-bd23-11ea-9a29-10837072aa6a.JPG)

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, have you updated ubermag? To be sure you have the most recent version, please run:
```
conda install --channel conda-forge ubermag=0.23
```

**Comment by marijanbeg** [comment]
Did this work for?

**Comment by gaurav123shukla** [comment]
Yes sir, it worked.

**Comment by marijanbeg** [comment]
Great, thank you for letting us know. I am closing this issue now.
