### ISSUE TITLE
Initial Magnetization Value

### ISSUE THREAD

**Issue by ahsu83** [ubermag/workshop#44]
Hi Ubermag team,

I have a question related to the initial value in discretisedfield.Field. Why do we need to specify the initial value of magnetization if we want to minimize the energy and get the stable spin texture at the end? Like in vortex we started from the $$(m_{x}, m_{y}, m_{z}) = (-cy, cx, 10)$$ and for skyrmion, we started from magnetization pointing down in the core and points upward away from the core and then we stabilize this initial magnetization configuration. I am not sure if I am correct, I was thinking that at least in the case of a skyrmion in the presence of DMI, the spin texture should end up in a skyrmion at the end whatever the initial magnetization.

**Comment by catrevil** [comment]
Hi @ahsu83!

I think it might be better if you posted the question [here](https://github.com/ubermag/help), as they're trying to have this space only be used while the workshops were running. By posting these sorts of things in the `ubermag/help` repository, it makes for a much lower level of management being necessary. I have a good answer for you if you're able to "migrate" this over there!

I hope this does not seem too egregious of a request from me :)

**Comment by ahsu83** [comment]
Hi Catrevil,

Thanks for your suggestion. Yes, I will move it to help. Thanks for letting me know.

**Comment by marijanbeg** [comment]
Thank you for moving your issue to help repository. We are still monitoring this repository for questions, but asking questions in our help repository is our recommendation, so other users who did not attend the workshop can benefit from it.
