### ISSUE TITLE
How we apply external field in some range with some step

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#45]
Dear sir
If i want to make hysterisis curve, we need to apply external field in range, e.g. -1 to 1Tesla with step 0.1 T(say). How we can create this script in jupyter notebook.

**Comment by gaurav123shukla** [comment]
Sir by mistake i posted it. please close the issue.

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, no problem. I hope you managed to solve this issue.

**Comment by gaurav123shukla** [comment]
Yes sir, i have solved. Eventually in problem #53 , it was discussed.

**Comment by marijanbeg** [comment]
Great!
