### ISSUE TITLE
 Docker installation

### ISSUE THREAD

**Issue by Jyotisaini-jnu** [ubermag/workshop#46]
Hello Sir...... First of all thank you so much for these amazing Ubermag sessions . 
I have followed the steps for installation of Docker in Windows 10 home :

Step 1.) Windows update to 2004 (update is available);

Step 2.) Enable : a.) Virtual machine platform;
                          b.) Windows Hypervisor Platform;
                          c.) Windows Subsystem for Linux;

Step 3.) Download and install the latest WSL2 Linux kernel; 

Step 4.) Download and install Docker-Desktop.

Finally ....I have "Docker-Desktop"  icon on my windows desktop.......But i don't further steps like: 
1.) Requirement of Docker ID and Password is necessary to Run Docker.
2.) Which command is used to link it with Ubermag.
3.) Use of  Docker-Dashboard Command  w.r.t  Ubermag.

I am attaching the initial Settings..... Please guide me for further steps and what i have to do next to attach it with Ubermag. Is your third session Docker Run command enough with these initial settings (as shown in attached word file) ?or I have to change some settings/options ........

Word File:

[Docker.docx](https://github.com/ubermag/workshop/files/4885196/Docker.docx)

Thankyou

**Comment by catrevil** [comment]
Hi @Jyotisaini-jnu !

To my knowledge, there's no need to configure a WSL 2 Linux Kernel & integrate it into your Windows 10 system. This is not a bad thing, but as far as I know, you do not need to go as above and beyond as you have done. This does, however, give you a nice Linux development kernel within your Windows OS, which is, in my opinion, pretty neat!

I would say that with installing Docker Desktop, you should only need to go as far as being able to run the command
````
docker run hello-world
````
in your Windows command-line utility (I recommend using Microsoft's Terminal utility for this--let me know if you're interested in this & I can direct you, it provides nice integration with the WSL kernels & looks very pretty!). I am not aware of whether a docker account is necessary for this or not.

After successful installation of Docker Desktop to the degree such that you can run the above command in `cmd` or related utility, and with an updated ubermag version to 0.23, you will find useful information in this notebook:

https://github.com/ubermag/workshop/blob/master/tutorials/choosing-runner.ipynb

So, let me try to be concise:

1. Install Docker Desktop to where you can run `docker run hello-world` in the windows command-line utility
2. Ensure your ubermag is fully updated to 0.23 within your ubermag environment
3. Run the linked notebook to see if everything works as expected (you should be able to explicitly call the docker runner and equally function as if there is no need to explicitly call it, as the process is automated)

FYI when you first call the docker runner, it will take a bit of time, perhaps a minute or more, while the docker image is pulled down and built on your local machine, after this, it will take mere seconds to run.

Please, if this does not make sense, let me know how I can clarify it further?

**Comment by marijanbeg** [comment]
Hi @Jyotisaini-jnu, thank you for your question. I agree with @catrevil - if you install Docker and it is running, that's it. You do not need to log in to DockerHUB.

**Comment by Jyotisaini-jnu** [comment]
Hi @marijanbeg and @catrevil  Sir.....Thanks for the replies. Actually ....after first try of Docker installation WSL 2 Linux Kernel failed comes in a dialogue box....... So, i thought may be it is important to install WSL2 . So...I reinstalled Docker  with WSL 2 Linux Kernel.....

**Comment by Jyotisaini-jnu** [comment]
Yes sir (@catrevil ) your guided steps are pretty clear to me ......Thank you ......I will try it and definitely let you know about further difficulties....

**Comment by marijanbeg** [comment]
Hi @Jyotisaini-jnu, have you managed to install Docker on your Windows machine?

**Comment by Jyotisaini-jnu** [comment]
Hello Sir (@marijanbeg ) everything is fine know and installed properly .....Thank you so much .....

**Comment by marijanbeg** [comment]
Great, thank you for letting us know.

**Comment by gaurav123shukla** [comment]
Hii jyotisaini-jnu
Has docker worked properly?
I am stuck with that in ubermag i could not run docker. Errors occured no such file or directory. If you solved prolem please tell me how you did.

**Comment by catrevil** [comment]
@gaurav123shukla do you have Docker Desktop installed? What platform are you running?

**Comment by gaurav123shukla** [comment]
Yes sir I have istalled docker desktop,aloso it is running.I am using windows 10 machine.

**Comment by catrevil** [comment]
@gaurav123shukla great! And are you successful when you run the
````
docker run hello-world
````
command?
What version of ubermag/oommfc are you running (what version is listed when you run `conda list`)?

For both of these questions, you are best to run them within your conda ubermag environment. That is, within a conda command prompt, you will write
````
conda activate ubermag
````
to access the environment that you made when you installed ubermag via miniconda.

If you do not understand any of these parts, please, let me know?

**Comment by Jyotisaini-jnu** [comment]
Hi @gaurav123shukla .......I have just installed Docker and run the above mentioned command" docker run hello-world" in Anaconda Prompt, steps are shown in the attached word file including update check. But i did not run the codes yet.....Whenever i will run the commands i will tell you...Thankyou

[Docker  run hello world command.docx](https://github.com/ubermag/workshop/files/4906731/Docker.run.hello.world.command.docx)

**Comment by gaurav123shukla** [comment]
Thanks you so much.

**Comment by gaurav123shukla** [comment]
Thanks sir :
Docker is working now ( when i run oommf a notification comes from the side of docker to" share" and no error such as above as i asked ).But sir for the crystal class Cnv again run time error is ocuuring. 
![run time skyrmion](https://user-images.githubusercontent.com/67150548/87225429-f306bf00-c35a-11ea-9e54-1d6a1efff82c.JPG)
Here sir I am sending ipynb file. Please sir check in your machine that error is occuring or not. 
[skyrmion.zip](https://github.com/ubermag/workshop/files/4906850/skyrmion.zip)

**Comment by catrevil** [comment]
@gaurav123shukla what version of ubermag/oommfc are you running? I know what your issue is & how to fix it depending on the answer to this question I have asked :)

Within your conda ubermag environment, you would run `conda list`, then tell me the associated version numbers :)

**Comment by gaurav123shukla** [comment]
Thanks sir for giving hope to me ;
Here i am attaching my conda list.Please find attachment
![list](https://user-images.githubusercontent.com/67150548/87228030-97ddc800-c36c-11ea-94e6-99ba03923f9d.JPG)
![list2](https://user-images.githubusercontent.com/67150548/87228031-9a402200-c36c-11ea-9f7a-2c00e82bcbf9.JPG)
![list3](https://user-images.githubusercontent.com/67150548/87228033-9e6c3f80-c36c-11ea-9868-e9421ca5a04d.JPG)
![list4](https://user-images.githubusercontent.com/67150548/87228035-a0360300-c36c-11ea-81f7-92b01d7d31c0.JPG)

**Comment by catrevil** [comment]
It looks like you don’t have Docker installed in that environment. Also, I notice you are still in (base), it is highly recommended you have a dedicated (ubermag) environment to run ubermag, so that you can avoid any compatibility issues or clashing modules/packages.

**Comment by gaurav123shukla** [comment]
Sir 
When i have to open jupyter notebook; I do open anoconda prompt cell , the i type conda activate ubermag then base change to ubermag and the type jupyter notebook.  My apology sir, I send above jpg pictures without activate ubemag. 
Sir how we installed docker in above mentioned ubermag. Sir one thing i want to mention here that always this error not occuring. In example of skyrmion disk ( docker tutorial in last session) succesfully run without docker and without any run time error.

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, the error you get actually is thrown by OOMMF because the initial magnetisation state you defined is not valid. It has nothing to do with docker or ubermag. I would suggest you have a look more carefully at the examples we provide. Unfortunately, from the `m_init` function, I cannot figure out what initial state you wanted to use. Maybe if you give me more details about what state you want.

I see there is a duplicate question on this topic from you in open issues, so I am going to close that one. Please feel free to continue discussion here.

**Comment by catrevil** [comment]
@marijanbeg it seems that it throws the same error as it would have before, when the `tcloommfrunner` on Windows was unable to handle the additional crystal class definitions.

Is there a way to make the error more explanative?
Or is it that it is the same error as before because it is also not a valid magnetic state/input to oommf?

**Comment by gaurav123shukla** [comment]
Thanks sir, now it is fine , I was incorrect in initial magnetization.
