### ISSUE TITLE
Asking about the manual of ubermag 

### ISSUE THREAD

**Issue by mzubair1** [ubermag/workshop#47]
Hello Professor
I have a question. Do you create a manual for the ubermag? I want to see the meaning of term like rerr and other terms similar to it?? Thanks

**Comment by marijanbeg** [comment]
Hi @mzubair1, thank you for your question. Absolutely, all functionality of Ubermag is documented.

As you have probably noticed, ubermag is a collection os subpackages, so documentation is split among different subpackages. We have a webpage dedicated to explaining that: https://ubermag.readthedocs.io/en/latest/ipynb/documentation.html

I am going to close this issue now, but if there is anything else you would like to ask related to this topic, or my answer does not make sense, please feel free to reopen this issue.
