### ISSUE TITLE
Simulation of skyrmionic structure in synthetic antiferrromagnet

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#48]
Dear sir
Do you have any ipynb file related to skyrmionic structure simulation in synthetic antiferromagnet(like triple layerd structure).If possible, please attach it sir. Sir in layered structure(as you gave example of rkky interaction in last session) i am stuck in which region we should take intial magnetization to relax in skyrmion and all other things. If you already have then please send it sir otherwise no issue sir. Thanks a lot sir:

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, we do not have a tutorial on this topic, but all the necessary ingredients should be there (exchange, RKKY, etc.) I suggest you just try to do it starting from those tutorials.

Regarding initial magnetisation, you need to set it in all subregions of your sample. If you expect to get a skyrmion, then initialising the system with something which looks like a skyrmion should be sufficient.

**Comment by gaurav123shukla** [comment]
Yes sir; I took help from rkky interraction file. But sir when I run the oommf ,some error ocuured. Sir I have also started docker but same error is showing. Sir i am sending ipynb file for same, please check sir it whether it is running in yor machine or not,so that i would  know where I am making mistake. 
[Ta_CFA_MgO.zip](https://github.com/ubermag/workshop/files/4891233/Ta_CFA_MgO.zip)
