### ISSUE TITLE
No such file or directory 'docker'

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#49]
Dear sir 
What i should for it. Please suggest me sir.
![dock](https://user-images.githubusercontent.com/67150548/87069143-b0bb7180-c1e4-11ea-94dc-71695c7ea8bb.JPG)
![dock1](https://user-images.githubusercontent.com/67150548/87069189-c2047e00-c1e4-11ea-942d-a43170ed779f.JPG)

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, do you have docker (https://www.docker.com/products/docker-desktop) installed?

**Comment by marijanbeg** [comment]
This issue is resolved - the issue was in invalid initial magnetisation state definition.
