### ISSUE TITLE
k3d not plotting

### ISSUE THREAD

**Issue by p-brane** [ubermag/workshop#50]
Hi @marijanbeg 
I'm seeing that k3d is not plotting. I get the following output:

`Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[2, -3, 0.2, 0.0, 0…
Output()`

I did the following:
* updated ubermag with` conda update ubermag`
* `jupyter nbextension install --py --sys-prefix k3d`
* `jupyter nbextension enable --py --sys-prefix k3d`

Jupypter nbextension reports the following.

`(ubermag) C:\Users\<user>\Documents\cad_jay\ubermag>jupyter nbextension list
Known nbextensions:
  config dir: C:\ProgramData\Miniconda3\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: problems found:
        - require?  X jupyter-js-widgets/extension
      k3d/extension enabled`

Would you suggest how to get k3d to plot?

**Comment by marijanbeg** [comment]
Hi @p-brane, are you using Jupyter or JupyterLab?

**Comment by p-brane** [comment]
Hi @marijanbeg 
Jupyter

**Comment by marijanbeg** [comment]
Hi @p-brane, is this issue resolved or it still needs addressing? If not, please reopen this issue.
