### ISSUE TITLE
Jupyter notebook path

### ISSUE THREAD

**Issue by p-brane** [ubermag/workshop#51]
Hi @marijanbeg ,
How does Jupyter notebook paths work?
I copied index.ipynb to my ubermag directory `../ubermag`. I used GitDeskop, cloned the workshop repository to my computer, and copied the tutorial files to my `../ubermag/notebooks/` directory. 

When I run the index.ipynb file from `../ubermag/ and click on the magnetization-field link I get a 404 error. The link goes to `http://localhost:8888/notebooks/magnetisation-field.ipynb`

When I go to my `../notebooks` directory the link shows `http://localhost:8888/notebooks/notebooks/magnetisation-field.ipynb`. There seems to be a double notebooks in the path.

**Comment by marijanbeg** [comment]
Hi @p-brane, thank you for your question. `index.ipynb` is just a convenience file which gives an overview of all notebooks so they can be opened from a single notebook. Each link to a notebook is actually a relative path to a notebook and the way I wrote them, it is assumed that all notebooks live in the same directory. So, if you want to use `index.ipynb` to open notebooks, please make sure they are all in the same directory as `index.ipynb`. Alternatively, you can change the relative paths in the markdown cell.

I am going to close this issue now, but please let me know if anything does not make sense.
