### ISSUE TITLE
Module 'micromagneticmodel' has no attribute 'RKKY'

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#53]
Dear sir
The example in last session on rkky is not running on my jupyter notebook. Is there is something to do else for it.
![RKKY](https://user-images.githubusercontent.com/67150548/87251369-359ec900-c439-11ea-9f4d-ea10783d3dd0.JPG)

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, you need to update your Ubermag installation. In the right conde environment, please run: `conda install --channel conda-forge ubermag=0.24`.
