### ISSUE TITLE
Hysteresis loop in Synthetic AFM

### ISSUE THREAD

**Issue by PkRPintu** [ubermag/workshop#55]
Hi,

Has anyone tried to perform hysteresis loop in ubermag? I was trying to perform the same in a synthetic antiferromagnetic model and I was unsuccessful. Could anyone try to let me know where I am doing the mistake or what is the problem? Again, if I do the same in a single ferromagnetic model it works perfectly fine. Now, I am confused. I attach the notebook file here. Thanks.
[SAF_Hysterisis.pdf](https://github.com/ubermag/workshop/files/4933024/SAF_Hysterisis.pdf)

**Comment by marijanbeg** [comment]
Hi @PkRPintu, thank you for your question. Code-wise everything looks fine to me apart from a few unnecessary complications I am going to address later. However, thing which most probably is causing problems is the lack of asymmetry in the simulated system which leads to numerical issues. More precisely, everything in your energy equation wants magnetisation out-of-plane and then applying field in the same direction to simulate hysteresis does not work. The symmetry is usually broken by tilting the applied field slightly and/or modifying your energy equation (by tilting anisotropy or adding demag).

I can see in the notebook you sent that you hardcoded the list for external field values. Please have a look at `linspace` or `arange` functions in `numpy` which can help you make those lists much easier.

I hope this answers your question. If not, please feel free to reopen this issue.

**Comment by PkRPintu** [comment]
Hi @marijanbeg  Thanks a lot for the help and useful instructions. This actually helped and now it works.
