### ISSUE TITLE
how to use mumax3c

### ISSUE THREAD

**Issue by Lee-89757** [ubermag/workshop#56]
Hi, @marijanbeg 
I'm trying to use ubermag based on mumax3c but find that I cannot import mumax3c. Here's the error report.

![image](https://user-images.githubusercontent.com/67505876/87775853-59a74380-c859-11ea-9f55-406b6d896e59.png)

How can I use mumax3 in ubermag?

**Comment by marijanbeg** [comment]
Hi @Lee-89757, thank you for your question. Please keep an eye on this issue where we are going to announce when the release is made : https://github.com/ubermag/help/issues/62

**Comment by Lee-89757** [comment]
Thank you very much for your help!
