### ISSUE TITLE
Field to energy value conversion

### ISSUE THREAD

**Issue by PkRPintu** [ubermag/workshop#57]
Hi, 

Does anyone know how to convert the values of Uniaxial Anisotropy strength (K) and RKKY exchange coupling strength (sigma) from field to energy. I know the values in Tesla or A/m and want to convert it to Joules/m^3 for Uni Axial Anisotropy (K) and Joules/m^2 for RKKY strength (sigma) to use in the Ubermag simulation. I am used to these terms in field units and first time switching to energy term for the simulation purpose, so please do let me know. Thanks a lot for the help.

Best wishes

**Comment by marijanbeg** [comment]
Hi @PkRPintu, I think I am not sure I understand you question. The energy density (J/m3) you can get directly by multiplying magnetisation and effective field (A/m). Alternatively, you can directly call `oc.compute` function. Please refer to tutorials from the workshop for details and slides for relevant formulas.

Does that answer your question? If not, please reopen the issue.
