### ISSUE TITLE
Multilayer structure

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#58]
Respected sir
I am simulating Ta(10)/Co2FeAl(5)/MgO(2) multilayer structure. Sir in literature the value of A, Ms, D are given. I initialize my system to formation of skyrmion. Since Ta will provide SOC so I think D value written for onlyfor r1 and r2 region. A, K, Ms value is for Co2FeAl because it is ferromagnet. So I write it as follows
![ta](https://user-images.githubusercontent.com/67150548/88270047-0a22a680-cca3-11ea-9740-f500cd7a71e3.JPG)
![ta1](https://user-images.githubusercontent.com/67150548/88270196-41915300-cca3-11ea-94fe-350bfc57a30d.JPG)
Sir please suggest me I am doing correct way or not. Please give me suggestion regarding this. 
Thank you so much sir.

**Comment by marijanbeg** [comment]
When you define a dictionary with parameter values, please make sure to define it in all subregions, even though its value is zero. For easier definition, you can use default. for example: `A = {'r1': 1e-12, 'default': 0}`.

**Comment by code-whale** [comment]
Hi@gaurav123shukla ,I saw that you set the initial state of the system to Skyrmion, could you please tell me how you defined the function? Thank you!

**Comment by marijanbeg** [comment]
Hi @code-whale, Python function should represent the mathematical fucntions. For instance:

```
def _init(pos):
        x, y, z = pos

        # polar coordinates
        rho = (x**2 + y**2)**0.5
        phi = np.arctan2(y, x)

        m_phi = np.sin(k * rho)
        m_z = -np.cos(k * rho)

        return (-m_phi*np.sin(phi), m_phi*np.cos(phi), m_z)
```

and by adjusting `k`, you change the helical period. I hope this makes sense.

**Comment by code-whale** [comment]
Hi@marijanbeg ,your answer has solved my problem. Thank you very much for your kind help!
