### ISSUE TITLE
Variation of skyrmion size with D and H value

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#59]
Dear sir
How can find and  plot size of skyrmion with variation of D or H with some step. If possible please give any python file containing same. Thanks sir.

**Comment by marijanbeg** [comment]
hi @gaurav123shukla, thank you for your question. You can probably sample the skyrmion profile on the line and then fit the sine/cosine function to it. From a fitted function, you can extract the period and accordingly the skyrmion size.

For more details, please refer to: https://www.nature.com/articles/srep17137

**Comment by gaurav123shukla** [comment]
Respected sir
 I read full paper as you suggest but sir literally i am saying, i can not write for initial configuration for skyrmion with helical period and how mz(x) can plot with diameter. Sir I request to you  please provide me a ipynb file for it so that i can learn how i can write initial configuration for different types of skyrmion and plot of mz(x). Only for learning how to write python file for such type of problem i am requesting for it. Sir first time I knew about micromagnetic simulation from your tutorial so i am begginer and new in python , but I am continuously try to learn it.
