### ISSUE TITLE
Effect of initial magnetization

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#61]
Dear sir
Why i am getting different result by taking initial magnetization random and second time in (1, 0, 0) direction. My anisotropy in (1, 1, 1) direction and some value of other parameter. When i set initial magnetization in (1, 0, 0) direction i got topological charge 0.08 while on taking initial mag in random direction i got topological charge 0.26. Then how can i justify which result is correct.

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, what relaxed state you get depends strongly on the initial state you use. Relaxation yields a local energy minimum and there are often many of them in the energy landscape. In summary, there could be many equilibrium states in the system for the same set of initial parameters.
