### ISSUE TITLE
Running too long using preinstalled OOMMF

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/workshop#64]
Hi,

I am running Ubermag with a preinstalled OOMMF in Tcl. My code seems to be taking five times as much time as the examples I have seen. Can this be remedied?

Regards

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, thank you for your question. This should not be the case. What operating system do you use? Is this the case for larger simulations as well. You can check the overhead Ubermag adds to simulations by running:
```
import oommfc
oommfc.oommf.overhead()
```

**Comment by AkravasTheWise** [comment]
Hi, @marijanbeg and thanks for your quick answer . I am in Windows 10 64 bit. For larger simulations it also takes longer. The overhead from Ubermag is around 0.45. However, in constrast to your examples from the docs, I get the following:

Running OOMMF (TclOOMMFRunner) [2020/08/25 11:19]... (9.6 s)

So, It runs it from Tcl instead of the exe runner and takes five times longer. Could that be the problem?

**Comment by marijanbeg** [comment]
Thank you for the clarification. Technically, this could be causing the delay, but I think this is not Ubermag-related problem. To use `ExeOOMMFRunner`, you can install Ubermag via conda.
