### ISSUE TITLE
Negative value of anisotropy

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#65]
Dear sir
Can i use negative value of Uniaxial anisotropy for simulation.
Actually whole story is that if i am using 0.3 MJ/m3 for simulation i am getting spin in (111) direction. I thought if easy axis is the in (111) so it is in plane and I should use it with sign. When i put k=-0.3 MJ/m3 i got chiral magnetic structure support our eperimental results. But i am not sure about sign.

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, thank you for your question. Using negative value for K in uniaxial anisotropy defines an easy-plane anisotropy. More precisely, it tends to align the magnetisation perpendicular to the anisotropy axis u. On the other hand, if K is positive, it tends to align the magnetisation parallel to the anisotropy axis. Please refer to the presentation slides we used at the beginning of the workshop, where we showed some examples.
