### ISSUE TITLE
Ubermag in Jupyter Lab

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/workshop#67]
Hi,

I was wondering if Ubermag has compatibility issues with Jupyter Lab. It completes the calculations successfully, but the plot doesn't show up. The output of the cell is something like this:

`Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[2, -3, 0.2, 0.0, 0…
Output()`

Thanks in advance.

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, thank you for your question. This is a known issue and it is the limitation of `k3d` (one of the Ubermag dependencies) at the moment and it has been reported. Unfortunately, this is something which is not in our power to fix and we have to wait for it to be resolved.

You can keep an eye here; https://github.com/K3D-tools/K3D-jupyter/issues/226
