### ISSUE TITLE
paralization in ubermag

### ISSUE THREAD

**Issue by Lee-89757** [ubermag/workshop#68]
Hi,

I was wondering how to set the number of compute threads in ubermag for oommf. As I know, I can use command line option -threads to oxsii in ommf but I cannot find the corresponding parameter settings in ubermag. 

Thank you

Lee

**Comment by marijanbeg** [comment]
Hi @Lee-89757, thank you so much for your patience - Ubermag 0.50 is out and provides this functionality.

Please update Ubermag (`conda update ubermag`) and have a look at this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/parallel.ipynb

Please note that there are many new functionalities and (some minor) changes in the interface, so you might want to have a look at other tutorials as well.

If you require any further support, please raise an issue in this repository, and we would be happy to address it.
