### ISSUE TITLE
The arrows indicating magnetization cannot appear in the 2D mapping. How to make them appear? If we use periodic boundary condition in the xz plane, can we also add the demagnetization energy term? Thank you!

### ISSUE THREAD

**Issue by zuosl01** [ubermag/workshop#71]

**Comment by marijanbeg** [comment]
Hi @zuosl01, thank you for your question. I am not sure I understand whats is the plotting issue you encountered. Could you please give us more details - ideally a short failing example?

Regarding the second part of the question, `oommfc` does not support periodic boundary conditions and demagnetisation.

**Comment by zuosl01** [comment]
Thank you for your reply. The failing example is attached. There are not arrows in the mapping. I have a another question now. For the uniaxialAnisotropy, if the first anisortropy constant K1<0,  the second anisortropy constant K2>0, and the easy axis u is [100], how to express them? For example, if  K1=-3e4, K2=1e4, and the u is [100], is the following grammar right?
K1 = -3e4  # uniaxial anisotropy constant (J/m3)
K2 = 1e4
u = (1, 0,0)  # uniaxial anisotropy axis
mm.UniaxialAnisotropy(K1=K1,K2=K2, u=u))
![failing example](https://user-images.githubusercontent.com/77775789/105432321-671f0980-5c92-11eb-8e30-01dfcac7c685.jpg)
 Thank you very much! I am looking forward to your reply.

**Comment by marijanbeg** [comment]
Thank you for the clarification. It looks like the number of discretisation cells you are plotting is very large. `matplotlib` cannot plot so many arrows and keep the plot informative. You can reduce the number of cells to be plotted by passing `n`. For example: `system.m.plane('y', n=(20, 20)).mpl()`. You can also refer to this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/mpl-visualisation.ipynb. In addition, you can also consider reducing the number of discretisation cells in the mesh (if physically justified).

Regarding uniaxial anisotropy, you are right - this is the right way to define it.

Does this resolve your issue?

(Please note that we have a dedicated help repository: https://github.com/ubermag/help, where we encourage all users to raise issues for any Ubermag package.)

**Comment by zuosl01** [comment]
Thank you for your reply. My issue is resolved.

**Comment by marijanbeg** [comment]
Great, thank you for letting us know. If you have an interesting use case about how you use Ubermag and would like to share it with others, I am sure others would find it useful - you can write a tutorial and we can make it part of the documentation.
