### ISSUE TITLE
Hysteresis Loops

### ISSUE THREAD

**Issue by MehranSedrpooshan** [ubermag/workshop#72]
Hello!

I am able to plot hysteresis loops through "NanoHub.org" but not on my machine (Windows). Also, standard question 1 is not included in the oommfc documentation.

So, how can I plot hysteresis loops?

Thanks!

**Comment by code-whale** [comment]
@MehranSedrpooshan ,I think you can learn how to draw the hysteresis loop and choose the corresponding solver in 

https://github.com/ubermag/workshop/blob/master/tutorials/hysteresis.ipynb 
Ubermag team made an important update to the software 20 days ago, adding a lot of helpful projects! If you want to use the program in this tutorial to draw hysteresis loops, you should upgrade ubermag to the latest version

**Comment by marijanbeg** [comment]
Hi @MehranSedrpooshan, thank you very much for your question. As @code-whale already pointed out, there is a dedicated tutorial for simulating hysteresis.

We do not support running Ubermag on NanoHub. If you would like to run Ubermag in the cloud, please use the Binder service (https://mybinder.org/v2/gh/ubermag/ubermag/HEAD?filepath=docs%2Fipynb%2Findex.ipynb).

@code-whale, thank you very much for helping others - much appreciated!!!
