### ISSUE TITLE
dipole-dipole interactions

### ISSUE THREAD

**Issue by zuosl01** [ubermag/workshop#73]
Dear professor，

    How to add the dipole-dipole interaction in  the simulation and change its value?

 Thank you very much!

**Comment by marijanbeg** [comment]
Hi @zuosl01, dipole-dipole interaction is demagnetisation. You can add it to the energy equation by adding `mm.Demag()` energy term.

Please refer to some of the tutorials for details. Apart from that, please note that we have a dedicated help repository (https://github.com/ubermag/help) and encourage all users to ask questions there.
