### ISSUE TITLE
Docker runner is not working

### ISSUE THREAD

**Issue by adnanphyqau** [ubermag/workshop#76]
Hello ubermag team, 
 Thanks for your help, i installed the docker and its giving this rum time error of OOMMF(attached). Kindly help me

P.S: i am running "Spatially varying parameters 2" from workshop.

![image](https://user-images.githubusercontent.com/32726982/115949267-42614a80-a4aa-11eb-9c90-21ba79412c1f.png)

**Comment by marijanbeg** [comment]
Hi @adnanphyqau, thank you for your question. You do not need any code in cell 7 and you do not need to specify runner in cell 8. Everything should happen automatically.

After you installed Docker, please just run the tutorial notebook in its original (without any modifications) and please let us know if you get any errors.

**Comment by adnanphyqau** [comment]
Thanks for your response! yes it works perfectly without runner command! moreover, i installed ubuntu from Microsoft play store WSL 2 kernel also (see https://docs.docker.com/docker-for-windows/wsl/ ). I was also able to run the code with the docker runner command also.
In summary, Docker must be in (Docker Desktop WSL 2 backend). One can check the docker is running in WSL 2 backend, like this (attached).
![image](https://user-images.githubusercontent.com/32726982/116010991-d7725980-a5f8-11eb-88ce-19d651905cb4.png)
PS: Mirijanbe, If needed I can made a demo for people.

**Comment by marijanbeg** [comment]
Great, thank you for letting us know @adnanphyqau. If you could make a tutorial for other users, that would be amazing. We can make it part of our official documentation and acknowledge you as the contributor to Ubermag.

I am going to close this issue now, but please open a new issue regarding any discussion about the tutorial you want to make.

**Comment by zzyzm123** [comment]
> Thanks for your response! yes it works perfectly without runner command! moreover, i installed ubuntu from Microsoft play store WSL 2 kernel also (see https://docs.docker.com/docker-for-windows/wsl/ ). I was also able to run the code with the docker runner command also.
> In summary, Docker must be in (Docker Desktop WSL 2 backend). One can check the docker is running in WSL 2 backend, like this (attached).
> ![image](https://user-images.githubusercontent.com/32726982/116010991-d7725980-a5f8-11eb-88ce-19d651905cb4.png)
> PS: Mirijanbe, If needed I can made a demo for people.

I do need some help with docker runner tutorials.
