### ISSUE TITLE
#TOPOLOGICAL CHARGE ATTRIBUTE ERROR

### ISSUE THREAD

**Issue by shivanirstogi** [ubermag/workshop#81]
Dear Sir,

Hope you are doing well in this pandemic situation. I am facing issue in calculation of topological charge for my program. It is showing attribute error all the time i use the command for calculating the same. Kindly, help me in resolving this problem.

System.m.plane(z=49e-9).topological_charge()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-3eb339ad861b> in <module>
----> 1 System.m.plane(z=49e-9).topological_charge()

~\miniconda3\envs\ubermag\lib\site-packages\discretisedfield\field.py in __getattr__(self, attr)
    673         else:
    674             msg = f'Object has no attribute {attr}.'
--> 675             raise AttributeError(msg)
    676 
    677     def __dir__(self):

AttributeError: Object has no attribute topological_charge.
[practice1 - Jupyter Notebook.pdf](https://github.com/ubermag/workshop/files/6662276/practice1.-.Jupyter.Notebook.pdf)

**Comment by lang-m** [comment]
Hi @shivanirstogi, we have changed the interface for computing topological charge in the last release. `topological_charge` is now in `discretisedfield.tools()`:
```Python
import discretisedfield.tools as dft
dft.topological_charge(system.m.plane(z=49e-9))
```
Please have a look at the documentation for more details: https://discretisedfield.readthedocs.io/en/latest/ipynb/field-tools.html#1.-Topological-charge/topological-charge-density

**Comment by shivanirstogi** [comment]
Dear sir,

I am facing problem in assigning D2d DMI ...kindly help me regarding this.


Thanks & Regards

Shivani Rastogi

**Comment by shivanirstogi** [comment]
Dear sir,

I am facing problem in assigning D2d DMI ...kindly help me regarding this.


Thanks & Regards

Shivani Rastogi
