### ISSUE TITLE
Taking snapshot of relaxation mode

### ISSUE THREAD

**Issue by Mishrakishan** [ubermag/workshop#88]
Hi @marijanbeg 
I have three part questions: 

1. Given an initial condition I run the Mindriver to relax the state, for which I want to take the snapshots of intermediate state before it relaxes.

I tried running the time driver and saving the file in a drive as:

```
td = oc.TimeDriver()
td.drive(system, t=0.2e-9, n=200)

system.m.plane('z').mpl()
```

and the recalling the driver by,
```
import micromagneticdata as md

data = md.Data(system.name)

@df.interact(n=data[-1].slider(continuous_update=False))
def myplot(n):
    data[-1][n].z.plane('z').mpl.scalar(figsize=(10, 5), filter_field=system.m.norm)
```

I can see the minimized magnetic structure, but moving the slider, I see zero variation. something wrong?

2. I have been trying to simulate an **in-plane skyrmion** and respective dynamics in mumax. Would it be possible to do so  here considering the needful changes it takes?
3. Can I make changes in k3d.vector plots like adding colure gradient with spin, and shape of spins?

Much Thanks!

**Comment by fangohr** [comment]
Dear Mishrakishan,

The question is not entirely clear to me.

Your code example is not complete and thus cannot be executed. Please see https://fangohr.github.io/computing/smartquestion.html for some guidance how to phrase questions for support effectively.

Please use this repository to ask questions in the future: https://github.com/ubermag/help

To record intermediate configurations during the energy minimisation, please have a look at 
https://ubermag.github.io/documentation/notebooks/oommfc/mindriver-steps.html
